export const Colors: Record<string, string> = {
  normal: 'has-background-success has-text-info-light',
  fire: 'has-background-danger has-text-info-light',
  water: 'has-background-info has-text-info-light',
  electric: 'has-background-warning',
  grass: 'has-background-primary-dark has-text-info-light',
  ice: 'has-background-link-light',
  fighting: 'has-background-danger-dark has-text-info-light',
  poison: 'has-background-info-light',
  ground: 'has-background-warning-dark has-text-info-light',
  flying: 'has-background-danger-light',
  psychic: 'has-background-primary-light',
  bug: 'has-background-success-dark has-text-info-light',
  rock: 'has-background-primary has-text-info-light',
  ghost: 'has-background-light ',
  dragon: 'has-background-danger has-text-info-light',
  dark: 'has-background-grey has-text-info-light',
  steel: 'has-background-grey-lighter',
  fairy: 'has-background-warning-light',
};
